# Generated by Django 4.2.16 on 2024-10-30 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=255)),
                ('no_de_catalogo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_del_curso', models.IntegerField(verbose_name='Id del Curso')),
                ('ciclo', models.IntegerField(verbose_name='Ciclo')),
                ('sesion', models.CharField(max_length=50, verbose_name='Sesión')),
                ('mat_comb', models.IntegerField(verbose_name='Mat. Comb.')),
                ('clases_comb', models.CharField(max_length=255, verbose_name='Clases Comb.')),
                ('capacidad_inscripcion_combinacion', models.IntegerField(verbose_name='Capacidad Inscripción Combinación')),
                ('no_de_catalogo', models.CharField(max_length=50, verbose_name='No de catálogo')),
                ('clase', models.CharField(max_length=100, verbose_name='Clase')),
                ('no_de_clase', models.IntegerField(verbose_name='No de clase')),
                ('capacidad_inscripcion', models.IntegerField(verbose_name='Capacidad Inscripción')),
                ('total_inscripciones', models.IntegerField(verbose_name='Total inscripciones')),
                ('total_inscripciones_materia_combinada', models.IntegerField(verbose_name='Total de inscripciones materia combinada')),
                ('fecha_inicial', models.DateField(verbose_name='Fecha inicial')),
                ('fecha_final', models.DateField(verbose_name='Fecha final')),
                ('capacidad_del_salon', models.IntegerField(verbose_name='Capacidad del salón')),
                ('hora_inicio', models.TimeField(verbose_name='Hora inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora fin')),
                ('lunes', models.BooleanField(default=False, verbose_name='Lunes')),
                ('martes', models.BooleanField(default=False, verbose_name='Martes')),
                ('miercoles', models.BooleanField(default=False, verbose_name='Miércoles')),
                ('jueves', models.BooleanField(default=False, verbose_name='Jueves')),
                ('viernes', models.BooleanField(default=False, verbose_name='Viernes')),
                ('sabado', models.BooleanField(default=False, verbose_name='Sábado')),
                ('domingo', models.BooleanField(default=False, verbose_name='Domingo')),
                ('bloque_optativo', models.CharField(max_length=50, verbose_name='Bloque optativo')),
                ('idioma_impartido', models.CharField(blank=True, max_length=50, null=True, verbose_name='Idioma en que se imparte la materia')),
                ('modalidad_clase', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modalidad de la clase')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.materia', verbose_name='Materia')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.profesor', verbose_name='Profesor')),
                ('salon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.salon', verbose_name='Salón')),
            ],
        ),
    ]
