version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rust_app
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/database_name
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database_name
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

  db:
    image: postgres:16
    container_name: db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database_name
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d database_name"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
