version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rust_app
    environment:
      - RUST_BACKTRACE=1
      - DJANGO_API_URL=http://localhost:8001/api/cursos/  # Update with actual URL
    ports:
      - "8082:8082"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
