version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rust_app
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=debug
      - DJANGO_API_URL=https://97c5-2801-f0-20-da0-8464-6c55-cecc-391a.ngrok-free.app/api/cursos/  # Update with actual URL
    ports:
      - "8082:8082"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
