# Generated by Django 4.2.16 on 2024-11-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='grupo_academico',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Grupo académico'),
        ),
        migrations.AddField(
            model_name='curso',
            name='id_administrador_curso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='inter_plantel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='intercambio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='nombre_administrador_curso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='oficialidad_materia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='organizacion_academica',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Organización académica'),
        ),
        migrations.AddField(
            model_name='curso',
            name='plan_academico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='rol_profesor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rol Profesor'),
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion_clase',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sección Clase'),
        ),
        migrations.AddField(
            model_name='curso',
            name='sede',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='id_profesor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='bloque_optativo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bloque optativo'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='capacidad_inscripcion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capacidad Inscripción'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='capacidad_inscripcion_combinacion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capacidad Inscripción Combinación'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='clase',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Clase'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='clases_comb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Clases Comb.'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha_final',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha final'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha_inicial',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha inicial'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='mat_comb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mat. Comb.'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='no_de_catalogo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='No de catálogo'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='total_inscripciones',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total inscripciones'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='total_inscripciones_materia_combinada',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total de inscripciones materia combinada'),
        ),
    ]
