# Generated by Django 4.2.16 on 2024-11-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_curso_grupo_academico_curso_id_administrador_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='ciclo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciclo'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='id_del_curso',
            field=models.CharField(max_length=50, verbose_name='Id del Curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='no_de_clase',
            field=models.CharField(max_length=50, verbose_name='No de clase'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='sesion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sesión'),
        ),
    ]
