# Generated by Django 4.2.16 on 2024-11-15 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_curso_rol_profesor_remove_schedule_profesor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='adjunto',
        ),
        migrations.AddField(
            model_name='curso',
            name='rol_profesor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rol Profesor'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.profesor', verbose_name='Profesor'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.profesor', verbose_name='Profesor'),
        ),
    ]
