# Generated by Django 4.2.16 on 2024-11-15 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_curso_adjunto_curso_rol_profesor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='rol_profesor',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='profesor',
        ),
        migrations.AddField(
            model_name='curso',
            name='adjunto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_adjunto', to='app.profesor', verbose_name='Profesor Adjunto'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_titular', to='app.profesor', verbose_name='Profesor Titular'),
        ),
    ]
